export const crops = [
  {
    name: "Rice / Safe Harvest",
    risk: "LOW RISK",
    apy: "4-6%",
    price: "100 gUSD",
    returnLabel: "≈ 4-6%",
    asset: "USDY",
    protocol: "Mantle RWA USDY Route",
    shareLabel: "Shareable calm harvest proof",
    description: "RWA-backed USDY lane for conservative users who want stable yield, clear exits, and policy-first automation.",
    accent: "bg-emerald-50 text-[var(--primary-strong)] border border-emerald-200",
    tone: "steady",
  },
  {
    name: "Corn / Growth Field",
    risk: "MEDIUM",
    apy: "7-11%",
    price: "250 gUSD",
    returnLabel: "≈ 7-11%",
    asset: "mETH",
    protocol: "Mantle mETH Yield Route",
    shareLabel: "Shareable growth streak",
    description: "mETH yield lane for users who accept measured volatility in exchange for stronger compounding potential.",
    accent: "bg-amber-50 text-amber-700 border border-amber-200",
    tone: "balanced",
  },
  {
    name: "Chili / Boost Farm",
    risk: "HIGHER",
    apy: "12-20%",
    price: "500 gUSD",
    returnLabel: "≈ 12-20%",
    asset: "USDY/mETH",
    protocol: "Mantle Dynamic RWA Route",
    shareLabel: "Shareable spicy rebalance",
    description: "Dynamic RWA + mETH lane where the agent can recommend guarded rebalances only inside user-defined limits.",
    accent: "bg-red-50 text-red-700 border border-red-200",
    tone: "bold",
  },
] as const;
