export const crops = [
  {
    name: "Rice / Safe Harvest",
    risk: "LOW RISK",
    apy: "4-6%",
    price: "100 USDT",
    returnLabel: "≈ 4-6%",
    asset: "USDC",
    protocol: "Agni Stablecoin Route",
    shareLabel: "Shareable calm harvest proof",
    description: "Stablecoin lane for conservative users who want calmer yield exposure, clear exits, and policy-first automation.",
    accent: "bg-emerald-50 text-[var(--primary-strong)] border border-emerald-200",
    tone: "steady",
  },
  {
    name: "Corn / Growth Field",
    risk: "MEDIUM",
    apy: "7-11%",
    price: "250 USDT",
    returnLabel: "≈ 7-11%",
    asset: "WMNT",
    protocol: "Agni WMNT Growth Route",
    shareLabel: "Shareable growth streak",
    description: "WMNT growth lane for users who accept measured volatility in exchange for stronger compounding potential.",
    accent: "bg-amber-50 text-amber-700 border border-amber-200",
    tone: "balanced",
  },
  {
    name: "Chili / Boost Farm",
    risk: "HIGHER",
    apy: "12-20%",
    price: "500 USDT",
    returnLabel: "≈ 12-20%",
    asset: "USDC/WMNT",
    protocol: "Agni Dynamic LP Route",
    shareLabel: "Shareable spicy rebalance",
    description: "Dynamic stablecoin plus WMNT lane where the agent can recommend guarded rebalances only inside user-defined limits.",
    accent: "bg-red-50 text-red-700 border border-red-200",
    tone: "bold",
  },
] as const;
