import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { describe, it } from "node:test";

const pageSource = readFileSync(new URL("./page.tsx", import.meta.url), "utf8");
const farmerSource = readFileSync(new URL("../../../components/base/farmer-companion/index.tsx", import.meta.url), "utf8");
const launchSectionsSource = readFileSync(new URL("../../../components/launch/page-sections/index.ts", import.meta.url), "utf8");
const launchHeaderSource = readFileSync(new URL("../../../components/launch/page-sections/header-card.tsx", import.meta.url), "utf8");
const launchCanvasSource = readFileSync(new URL("../../../components/launch/page-sections/canvas-tab.tsx", import.meta.url), "utf8");
const launchShopSource = readFileSync(new URL("../../../components/launch/page-sections/shop-tab.tsx", import.meta.url), "utf8");
const launchAuditSource = readFileSync(new URL("../../../components/launch/page-sections/audit-tab.tsx", import.meta.url), "utf8");
const historySource = readFileSync(new URL("../../../components/sections/agent-history.tsx", import.meta.url), "utf8");
const vaultSource = readFileSync(new URL("../../../components/sections/garden-rwa-vault.tsx", import.meta.url), "utf8");

describe("Launch app game assistant UI", () => {
  it("renders a paper-style garden agent console connected to runtime API and live history", () => {
    assert.match(pageSource, /Start Here/);
    assert.match(pageSource, /Claim test funds/i);
    assert.match(pageSource, /Move funds into vault/i);
    assert.match(pageSource, /Allow agent/i);
    assert.match(pageSource, /Start autopilot/i);
    assert.doesNotMatch(pageSource, /At a glance/i);
    assert.doesNotMatch(pageSource, /Latest decision/i);
    assert.match(pageSource, /LaunchCanvasTab/);
    assert.match(pageSource, /LaunchAuditTab/);
    assert.match(pageSource, /FarmerCompanion/);
    assert.match(pageSource, /useGardenAgent/);
    assert.match(launchSectionsSource, /LaunchHeaderCard/);
    assert.match(launchSectionsSource, /LaunchCanvasTab/);
    assert.match(launchSectionsSource, /LaunchShopTab/);
    assert.match(launchSectionsSource, /LaunchAuditTab/);
    assert.match(launchHeaderSource, /Gardenaz/);
    assert.match(launchHeaderSource, /Run plan|Run agent/);
    assert.match(launchHeaderSource, /Finish setup|Agent ready/);
    assert.match(launchHeaderSource, /Plan/);
    assert.match(launchHeaderSource, /Vault/);
    assert.match(launchHeaderSource, /Proof/);
    assert.match(launchCanvasSource, /FarmScene/);
    assert.match(launchCanvasSource, /PlantedSummary/);
    assert.match(launchShopSource, /GardenRwaVaultSection/);
    assert.match(launchAuditSource, /Latest actions and on-chain record/);
    assert.match(launchAuditSource, /AgentHistorySection/);
    assert.match(farmerSource, /FarmerSpriteView/);
    assert.match(farmerSource, /Assistant/);
    assert.match(farmerSource, /Open assistant/);
    assert.match(farmerSource, /Quick actions/);
    assert.match(farmerSource, /stream: true/);
    assert.match(historySource, /useAgentHistory/);
    assert.match(vaultSource, /Move money in, let the agent work, pull money out when needed/i);
    assert.match(vaultSource, /Wallet/i);
    assert.match(vaultSource, /Vault/i);
    assert.match(vaultSource, /Next step/i);
    assert.match(vaultSource, /Deposit/i);
    assert.match(vaultSource, /Withdraw/i);
    assert.match(vaultSource, /Authorize/i);
    assert.doesNotMatch(pageSource, /AI Farmer Diary/);
    assert.doesNotMatch(pageSource, /Latest decisions/);
  });
});
