"use client";

import { useState, useEffect, useCallback } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { ArrowRight } from "lucide-react";
import Link from "next/link";
import { staggerContainer, staggerItem, easeOutExpo } from "@/lib/motion";

type Bird = {
  id: number;
  x0: number;
  y0: number;
  x1: number;
  y1: number;
  scale: number;
  delay: number;
  duration: number;
};

type AgentCard = {
  badge: string;
  title: string;
  subtitle: string;
  confidence: number;
  assignedTo: string;
};

const agentCards: AgentCard[] = [
  {
    badge: "Agent Output",
    title: "Strategy Review",
    subtitle: "Plan generated by agent",
    confidence: 77,
    assignedTo: "Garden Keeper",
  },
  {
    badge: "Yield Signal",
    title: "mETH Opportunity",
    subtitle: "Rate anomaly detected on Mantle",
    confidence: 84,
    assignedTo: "Yield Scout",
  },
  {
    badge: "Risk Alert",
    title: "Policy Gate Active",
    subtitle: "Guardrails verified — safe to proceed",
    confidence: 92,
    assignedTo: "Guardian Node",
  },
  {
    badge: "Proof Event",
    title: "ZK Attestation",
    subtitle: "Agent decision benchmarked on-chain",
    confidence: 69,
    assignedTo: "Verifier Node",
  },
];

function generateBirds(): Bird[] {
  const birds: Bird[] = [];
  for (let i = 0; i < 14; i++) {
    const fromLeft = Math.random() < 0.5;
    birds.push({
      id: i,
      x0: fromLeft ? -12 : 112,
      y0: 5 + Math.random() * 60,
      x1: fromLeft ? 112 : -12,
      y1: 10 + Math.random() * 55,
      scale: 0.4 + Math.random() * 0.8,
      delay: 0.2 + Math.random() * 2.5,
      duration: 6 + Math.random() * 12,
    });
  }
  return birds;
}

function BirdShape({ scale = 1 }: { scale: number }) {
  return (
    <svg width={14 * scale} height={6 * scale} viewBox="0 0 14 6">
      <path
        d="M0,3 Q4,0 8,3 Q12,0 14,3 Q10,2.5 7,3.5 Q4,2.5 0,3Z"
        fill="#111"
      />
    </svg>
  );
}

function BirdsLayer() {
  const [birds] = useState<Bird[]>(() => generateBirds());

  return (
    <div className="pointer-events-none absolute inset-0 z-[3] overflow-hidden">
      {birds.map((b) => (
        <motion.div
          key={b.id}
          className="absolute"
          initial={{ x: `${b.x0}%`, y: `${b.y0}%`, opacity: 0 }}
          animate={{ x: `${b.x1}%`, y: `${b.y1}%`, opacity: 1 }}
          transition={{
            x: { duration: b.duration, delay: b.delay, ease: "linear", repeat: Infinity },
            y: { duration: b.duration * 0.6, delay: b.delay, ease: "easeInOut", repeat: Infinity, repeatType: "reverse" },
            opacity: { duration: 0.4, delay: b.delay },
          }}
        >
          <motion.div
            animate={{ rotate: [-3, 3, -3] }}
            transition={{ duration: 0.3, repeat: Infinity, ease: "easeInOut" }}
          >
            <BirdShape scale={b.scale} />
          </motion.div>
        </motion.div>
      ))}
    </div>
  );
}

function AgentCardSwitcher() {
  const [index, setIndex] = useState(0);

  const next = useCallback(() => {
    setIndex((i) => (i + 1) % agentCards.length);
  }, []);

  useEffect(() => {
    const timer = setInterval(next, 4000);
    return () => clearInterval(timer);
  }, [next]);

  const card = agentCards[index];
  const direction = index % 2 === 0 ? 1 : -1;

  return (
    <motion.div
      initial={{ opacity: 0, y: 18 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ delay: 1.2, duration: 0.6, ease: easeOutExpo }}
      className="absolute bottom-8 left-1/2 z-[6] w-[300px] -translate-x-1/2"
    >
      <div className="absolute -top-2 left-[10px] right-[-10px] bottom-2 rounded-[14px] bg-white/60 rotate-[2deg]" />
      <div className="relative rounded-[14px] bg-white/96 px-[18px] py-4 shadow-[0_8px_32px_rgba(0,0,0,0.14),0_1px_4px_rgba(0,0,0,0.08)] overflow-hidden">
        <AnimatePresence mode="wait" custom={direction}>
          <motion.div
            key={index}
            custom={direction}
            initial={{ x: 40 * direction, opacity: 0 }}
            animate={{ x: 0, opacity: 1 }}
            exit={{ x: -40 * direction, opacity: 0 }}
            transition={{ duration: 0.35, ease: easeOutExpo }}
          >
            <div className="mb-[10px] inline-flex items-center gap-[5px] rounded-[20px] border border-[#c8e89a] bg-[#f0fce8] px-[10px] py-[3px] text-[10px] font-semibold text-[#4a8018] tracking-[0.3px]">
              <span className="text-[9px]">✦</span> {card.badge}
            </div>
            <div className="mb-[2px] text-[17px] font-bold text-[#111]">{card.title}</div>
            <div className="mb-3 text-[11.5px] text-[#888]">{card.subtitle}</div>
            <div className="mb-[6px] flex justify-between text-[10px] font-semibold text-[#aaa] tracking-[0.8px]">
              <span>CONFIDENCE</span>
              <span className="text-xs font-bold text-[#333]">{card.confidence}%</span>
            </div>
            <div className="mb-[14px] h-[7px] overflow-hidden rounded-[4px] bg-[#eee]">
              <motion.div
                className="h-full rounded-[4px] bg-[linear-gradient(to_right,#d4e840,#74c918)]"
                initial={{ width: 0 }}
                animate={{ width: `${card.confidence}%` }}
                transition={{ delay: 0.15, duration: 0.7, ease: easeOutExpo }}
              />
            </div>
            <div className="flex items-center justify-between">
              <div className="flex items-center">
                <div className="flex size-[30px] shrink-0 items-center justify-center rounded-full bg-[linear-gradient(135deg,#b8d4f0,#7aabdc)] text-[11px] font-bold text-[#2a5a8c]">
                  GA
                </div>
                <div className="ml-[10px]">
                  <p className="text-[11px] text-[#666]">Awaiting Approval</p>
                  <p className="text-[11px] text-[#666]">
                    Assigned to <strong className="text-[#222]">{card.assignedTo}</strong>
                  </p>
                </div>
              </div>
              <Link
                href="/app"
                className="flex size-[30px] items-center justify-center rounded-full border border-[#ddd] bg-white text-[11px] text-[#888] hover:bg-gray-50"
              >
                <ArrowRight className="size-3" />
              </Link>
            </div>
          </motion.div>
        </AnimatePresence>
      </div>
    </motion.div>
  );
}

export function HeroCloudReveal() {
  return (
    <section id="what-is-gardenaz" className="relative min-h-[90vh] w-full overflow-hidden">
      <video
        src="/bg-hero.mp4"
        autoPlay
        muted
        loop
        playsInline
        className="absolute inset-x-0 top-0 h-[calc(100%+3rem)] w-full object-cover"
      />

      {/* Dark gradient overlay for text readability */}
      <div className="pointer-events-none absolute inset-0 z-[2] bg-gradient-to-b from-black/55 via-black/35 to-black/65" />

      {/* White-to-transparent gradient block cover — top */}
      <div className="pointer-events-none absolute top-0 left-0 right-0 z-[7] h-20 bg-gradient-to-b from-white to-transparent" />

      {/* White-to-transparent gradient block cover — bottom */}
      <div className="pointer-events-none absolute bottom-0 left-0 right-0 z-[7] h-24 bg-gradient-to-t from-white to-transparent" />

      <BirdsLayer />

      {/* Text overlay */}
      <motion.div
        variants={staggerContainer}
        initial="initial"
        animate="animate"
        className="pointer-events-none absolute z-[5] top-[18%] left-1/2 w-[92%] max-w-[720px] -translate-x-1/2 text-center"
      >
        <motion.p
          variants={staggerItem}
          className="mx-auto mb-3 text-sm font-bold tracking-[3px] text-white/90 drop-shadow-[0_2px_8px_rgba(0,0,0,0.5)]"
        >
          AI x RWA AGENT ON MANTLE
        </motion.p>
        <motion.h1
          variants={staggerItem}
          className="mx-auto mb-5 text-[54px] font-extrabold leading-[1.08] -tracking-[1.5px] text-white drop-shadow-[0_4px_28px_rgba(0,0,0,0.45)] sm:text-[64px] lg:text-[72px]"
        >
          Grow Real Yield with
          <br />
          <span className="text-[#B3DF46] drop-shadow-[0_0_24px_rgba(179,223,70,0.35)]">AI That Proves Its Work</span>
        </motion.h1>
        <motion.p
          variants={staggerItem}
          className="mx-auto max-w-[540px] text-base leading-[1.75] text-white/85 drop-shadow-[0_2px_10px_rgba(0,0,0,0.45)] sm:text-lg"
        >
          Gardenaz gives you a transparent way to plant, monitor, and harvest agent-based yield strategies across RWA lanes, policy gates, and on-chain proof.
        </motion.p>
      </motion.div>

      {/* Floating Agent Card with switching animation */}
      <AgentCardSwitcher />
    </section>
  );
}
